Enrollment UI
CGATechnologies/sctp2 pull request #11
Opened 2022-10-20 03:18 UTC by sammymuriuki

Display household general information
Add main and alternate household recipients
Create new and edit school enrollment
Change enrollment status (to selected or enrolled )

2022-10-20 15:59 UTC, kamfosica requested changes
![image](https://user-images.githubusercontent.com/83751365/196998981-5ad084ca-be44-44f6-a945-e074f8241d83.png)

Can you pull latest changes from master and fix :point_up: . It's not loading alternative non-household details.

2022-11-22 11:49 UTC, kamfosica commented
Are we able to see alternate images?

Also, under the school enrollment. Only show household members that are between 5-25 years old (inclusive)

2022-12-02 08:38 UTC, sammymuriuki commented
> ![image](https://user-images.githubusercontent.com/83751365/196998981-5ad084ca-be44-44f6-a945-e074f8241d83.png)
> 
> Can you pull latest changes from master and fix point_up . It's not loading alternative non-household details.

This has been fixed

2022-12-09 17:26 UTC, kamfosica approved these changes

2022-12-09 17:27 UTC, merged