Data import review page improvements
CGATechnologies/sctp2 pull request #9
Opened 2022-09-13 11:01 UTC by kamfosica

Building upon PR #8 , this introduces improvement on the data import review page.

2022-09-13 13:34 UTC, zikani03 requested changes
Looks okay, just a couple of nitpicks

2022-09-13 13:41 UTC, kamfosica commented on sctp-mis/src/main/resources/public/components/DataImportReview.vue
> +                {{ props.row.cluserName }}
Nice catch. Was wondering why a recent import was 100% valid but cluster came up blank

2022-09-13 13:41 UTC, kamfosica commented on sctp-mis/src/main/resources/public/components/DataImportReview.vue
> +                {{ props.row.cluserName }}
Nice catch. Was wondering why a recent import was 100% valid but cluster came up blank

2022-09-13 13:42 UTC, kamfosica commented on sctp-mis/src/main/java/org/cga/sctp/mis/targeting/DataImportController.java
> +    private static final String[] CORS_HEADERS = {"X-Is-Slice",
Yeah. Will move into CorsConfiguration

2022-09-13 13:43 UTC, kamfosica commented on sctp-mis/src/main/java/org/cga/sctp/mis/targeting/DataImportController.java
> +            @RequestParam("household") Long householdId,
No problem

2022-09-13 19:00 UTC, kamfosica commented on sctp-mis/src/main/java/org/cga/sctp/mis/targeting/DataImportController.java
> +    private static final String[] CORS_HEADERS = {"X-Is-Slice",
Moved to config

2022-09-14 07:57 UTC, zikani03 approved these changes

2022-09-14 13:44 UTC, merged